GET http://localhost:8080/api/v1/posts/my
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyTmFtZSI6InRlc3QiLCJpYXQiOjE2NzU3ODE4MzgsImV4cCI6MTY3ODM3MzgzOH0.U-mEIRsvMzj5pRghK8N1aCqVqdBWN3Fh4OVoT4NOQfs